### ISSUE TITLE
Wine Cellar: wines not saving

### ISSUE THREAD

**Issue by Iofmanynames** [NathanielMotus/Cavevin#2]
Hi, great idea for an app! I tried using it but the wines I add aren't saving (they say they are, but when I close and re-open the app they are no longer there.)

**Comment by NathanielMotus** [comment]
Hi,

Thank you for your feedback ! Could you, please, let me know what are your Android version and phone model so that I can carry out tests ?

For now, I have no idea where the problem can hide, but I'll find out and let you know as soon as I solve it !

**Comment by Iofmanynames** [comment]
Hi, thank you for your response. My phone model is SM-A520W and the Android version is 7.1.2.

**Comment by NathanielMotus** [comment]
Hi,

I'm unable to reproduce this behaviour... Just in case, aren't you trying to save, for example, a white wine while red wine filter (the second of four patches at the bottom) is on ?

Don't take it bad if not :), but as I didn't make a user manual, it may not be clear for every one what these patches are made for !

**Comment by Iofmanynames** [comment]
Hi, I tried again to make sure that wasn't the problem. I am staying on red for the whole time in the following tests:

I created a new wine, took a screenshot, closed to program and then opened it again and took another screenshot so you can see what I am seeing. 

Then I did the same thing again to show screen shot of the stats, before and after closing and reopening...

**Comment by NathanielMotus** [comment]
Here's my mail : nathaniel.motus@laposte.net

Can you, please, send me your screenshots ?

**Comment by NathanielMotus** [comment]
I'll release a new version, so that we'll see if it works

**Comment by Iofmanynames** [comment]
Thank you

**Comment by felmab** [comment]
I tried the app (downloaded from F-Droid) on two different phones. When I close and open it again, no data appear, no matter how filters are configured.

**Comment by NathanielMotus** [comment]
Hi,

I will release a version that should solve this problem, but, just to be sure : how do you close the app ? With back button or by killing it ? And, by the way, what are these phones you tried ?

Nathaniel

Le 10 août 2020 15:40:12 CEST, felmab <notifications@github.com> a écrit :
>I tried the app (downloaded from F-Droid) on two different phones. When
>I close and open it again, no data appear, no matter how filters are
>configured.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NathanielMotus/Cavevin/issues/2#issuecomment-671360323

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by felmab** [comment]
> How do you close the app ? With back button or by killing it ?
By swiping it.

> And, by the way, what are these phones you tried ?
Samsung s5 and Xperia Z

**Comment by NathanielMotus** [comment]
Datas are saved when leaving the app regularly, i.e. by using back button. The update I will release shall surely solve your problem, but, as I'm far from my PC for now and as the release need to be analyzed and validated by F-Droid, I'm afraid it won't be available before mid September.

Le 10 août 2020 22:37:41 CEST, felmab <notifications@github.com> a écrit :
>> How do you close the app ? With back button or by killing it ?
>
>By swiping it.
>
>> And, by the way, what are these phones you tried ?
>
>Samsung s5 and Xperia Z
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NathanielMotus/Cavevin/issues/2#issuecomment-671577334

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by felmab** [comment]
I think I have the same issue when using the back button. Anyway, thanks in advance for the update, I'll test it when you release it. Passe un bon été !

**Comment by NathanielMotus** [comment]
Update is released ! Can you please tell me whether it works or not ?

**Comment by Iofmanynames** [comment]
Hi, yes, I meant to send you a message to thank you. It works!!!

**Comment by NathanielMotus** [comment]
Great ! I'm glad it works ! I hope you'll enjoy managing your wine before drinking it ;)

Le 30 août 2020 20:41:08 CEST, Iofmanynames <notifications@github.com> a écrit :
>Hi, yes, I meant to send you a message to thank you. It works!!!
>
>On August 30, 2020 2:40:31 AM CDT, NathanielMotus
><notifications@github.com> wrote:
>>Update is released ! Can you please tell me whether it works or not ?
>>
>>-- 
>>You are receiving this because you authored the thread.
>>Reply to this email directly or view it on GitHub:
>>https://github.com/NathanielMotus/Cavevin/issues/2#issuecomment-683387880
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NathanielMotus/Cavevin/issues/2#issuecomment-683455174

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by felmab** [comment]
> Update is released ! Can you please tell me whether it works or not ?

It does, thank you!

> I hope you'll enjoy managing your wine before drinking it ;)

They say drinking it is a great way to manage it ;-)

**Comment by NathanielMotus** [comment]
It is the best way ! And it doesn't suffer any bug :)

Le 31 août 2020 18:15:48 CEST, felmab <notifications@github.com> a écrit :
>> Update is released ! Can you please tell me whether it works or not ?
>
>It does, thank you!
>
>> I hope you'll enjoy managing your wine before drinking it ;)
>
>They say drinking it is a great way to manage it ;-)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NathanielMotus/Cavevin/issues/2#issuecomment-683879686

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
