### ISSUE TITLE
export to csv file

### ISSUE THREAD

**Issue by VincentBerree** [NathanielMotus/Cavevin#4]
Hi,
When I export to csv file, I can only see only half of the entries in the file.
I'm not an expert, but I think I found the issue in the for loop of exportCellarToCsvFile.
There are 2 "i++" in the loop.
```
for (int i=0;i<Cellar.getCellarPool().get(MainActivity.getCurrentCellarIndex()).getCellList().size();i++){
bw.append(cellToCsvLine(context,Cellar.getCellarPool().get(MainActivity.getCurrentCellarIndex()).getCellList().get(i))+"\n");
i++;
}
```

**Comment by NathanielMotus** [comment]
Hi,

I will fix this bug as soon as possible. Thank you for investigating ! this double i++ does not actually seem very relevant. There should be a new release within a fortnight.

**Comment by NathanielMotus** [comment]
I fixed it ! It should be available on F-Droid next week. But you can also download it directly from here.

I'll close this issue when you confirm it works well.

**Comment by VincentBerree** [comment]
It looks good. I can see all bottles in the export.
Thanks.
